### ISSUE TITLE
Error with case-sensitive usernames on login

### ISSUE THREAD

**Issue by MarcRoigVilamala** [dais-ita/cogni-sketch#10]
From some minor testing, I believe that usernames are not case-sensitive, with all letters being transformed to lower case.

As such, if I create a user called `marcRoig`, a user called `marcroig` is created instead. I think this should be indicated when creating the user.

More importantly, however, is that when I later try to log in with username `marcRoig`, it allows me to log in but it gives me an error because it cannot find my palettes, despite having initialised the user. Logging in with username `marcroig` works fine.

I believe this is because the system correctly identifies that I am trying to log into user `marcroig` but tries to access the folder and palettes for `marcRoig`, which leads to the error.

**Comment by davebraines** [comment]
Fixed in v0.1.9
Ensure all usernames are converted to lowercase when creating users and loggin in.
